@host = http://localhost:8080

### GET
GET {{host}}/actuator/health

### Test
GET {{host}}/api/v1/test

### Test
GET {{host}}/api/v1/test/abc

### 1) Tach chung thu DS tu SOD hop le -> 200
# @name parse
POST {{host}}/sod/parse
Content-Type: application/json

{
  "sod": "{{}}"
}

### Test virtual thread
GET {{host}}/api/v1/thread1
Accept-Language: vi

### Test virtual thread
GET {{host}}/api/v1/thread/virtual

### Test platform thread
GET {{host}}/api/v1/thread/platform

### Test
GET {{host}}/api/v1/test/request-param

### Test
GET {{host}}/api/v1/caffein/put

### Test
GET {{host}}/api/v1/caffein/get-if-present

### Test
GET {{host}}/api/v1/caffein/get

### Test
GET {{host}}/api/v1/caffein/invalidate

### Test
GET {{host}}/api/v1/randomuser/generate
