spring:
  application:
    name: template

  threads:
    virtual:
      enabled: true

  task:
    execution:
      thread-name-prefix: 'template-platform-async-'
      pool:
        core-size: 8 # Bằng số nhân CPU (đối với CPU-bound tasks)
        max-size: 16 # Tối đa 2x core-size để tránh lãng phí RAM/CPU Context Switch
        queue-capacity: 500 # Hàng đợi đủ lớn để chịu tải spike ngắn hạn

  jackson:
    # property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    mapper:
      sort-properties-alphabetically: false

  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: postgres
    password: postgres_password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true

# Monitoring & Health Check via Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.tcbs.template.client: DEBUG
  pattern:
    level: '%5p [${spring.application.name:-},%X{X-Request-ID:-}]'

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

client:
  randomuser-service:
    url: https://randomuser.me