server:
  port: 8080
  forward-headers-strategy: native
  shutdown: graceful # see https://docs.spring.io/spring-boot/reference/web/graceful-shutdown.html#web.graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring:
  # application:
  #   name: ${APP_NAME:template}

  threads:
    virtual:
      enabled: true

  task:
    execution:
      thread-name-prefix: ${spring.application.name}-platform-async-
      pool:
        core-size: 2 # Bằng số nhân CPU (đối với CPU-bound tasks)
        max-size: 50 # Tối đa 2x core-size để tránh lãng phí RAM/CPU Context Switch
        queue-capacity: 10000 # Hàng đợi đủ lớn để chịu tải spike ngắn hạn
    scheduling:
      thread-name-prefix: ${spring.application.name}-scheduling-
      pool:
        size: 2

  jackson:
    # property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    mapper:
      sort-properties-alphabetically: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:template}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 600000 # Thời gian hết hạn cache mặc định (tính bằng ms, ví dụ: 600000ms = 10 phút)
      cache-null-values: false # Không lưu giá trị null vào cache

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:} # Điền password nếu Redis server có bật auth
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

# Monitoring & Health Check via Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db

logging:
  level:
    io.tcbs.template.client: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    level: '%5p [${spring.application.name:-},%X{X-Request-ID:-}]'

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}

client:
  randomuser-service:
    url: ${RANDOMUSER_SERVICE_URL:https://randomuser.me}

application:
  topic:
    partitions: 3
